// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package nsxt

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "nsxt", asset.ModuleFieldsPri, AssetNsxt); err != nil {
		panic(err)
	}
}

// AssetNsxt returns asset data.
// This is the base64 encoded zlib format compressed contents of module/nsxt.
func AssetNsxt() string {
	return "eJx8j0HOgyAQhfec4sW9F2Dx7/6D0PJaiSgExlRv3yCtsdb02zETvvemRc9FY8yzKECceGo05dkoINHTZGpcKEYBlvmaXBQXRo0/BWD9iSHYyVMBN0dvs143LUYzcHMXZInUuKcwxdfkxPhp2Zs6Gi/dNj7zFY6t35xmVb7Mxwr7GpzNENdz99QuPZdHSPaw+5Fc+K/CGqqeAQAA///4VWoX"
}
