// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package purestorage

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "purestorage", asset.ModuleFieldsPri, AssetPurestorage); err != nil {
		panic(err)
	}
}

// AssetPurestorage returns asset data.
// This is the base64 encoded zlib format compressed contents of module/purestorage.
func AssetPurestorage() string {
	return "eJx8j0FuwyAURPecYuS9L8Ciux6ElqmFjA36YDXcPiKOI0ysvOV89GYYMbNoxE2YchAzUQHZZU+NoUkHBQg9TaLGD7NRgGX6FRezC6vGlwLQerAEu/mq+3P0NunHgxGrWdgXVnKJ1JgkbPGZXPjPslZoRExJr/jKV+n/cHDZtfNm7ie0M3gzS/Q83Y4tM8t/ENvdPjRXvnfhXqruAQAA//9r1XXf"
}
