// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package purestorage

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "purestorage", asset.ModuleFieldsPri, AssetPurestorage); err != nil {
		panic(err)
	}
}

// AssetPurestorage returns asset data.
// This is the base64 encoded zlib format compressed contents of module/purestorage.
func AssetPurestorage() string {
	return "eJzsWk1z2zYQvftX7OTUHtLedehMJj3Uh8Ru7KZHDUysLIxBAFksbau/vgOQovUBUIxEuG5GPORAKu897C4fFku/hwdczcA1hJ4tiXu8AGDFGmfwbuPuuwsAQo3C4wzukMUFgERfkXKsrJnBbxcAsIkDtZWNDnALhVr6WfzBezCixl3CcPHK4QzuyTauu5PA3wbbBBREYuX72ym8cO2uYX0ludprD3lXwta6kBaWamEq3Hqe05PD28QkFHJ+J4x8UpKXez9bQ2tr7hMPB1a2vr6gkNATgDJwt2L0YTHgsbJG/jIsTlnnS+m6vLq+gZ8ujWv416uGXcNw5ZBE+I8erpHgJkr8+YBGLRhNtSols4MPwauV1qqNm8+LeiLFWDStfweGY/PayiuU2FbZBJltVZZLbSv0YG733GiJQm/ldDI32kMecqNoXfPKGiarNdJkluRZcJOvjAdcPVmSx8X8JmKDXQAvsVsvVEusHrJywr9lxHwWNa6loGHF+1W2FvGI5JU1ZXR8bcFBmbi9cIpoLaS2slA0PlkZo2HXr+mgBl1OhAYlQzoWaqeotyu/tkaxna7so934uUOae6wK+M3npr5DCiFuqTasOiuq8VhFSa0Z2t1FTaHrk6rIdrYXNUWuEXVgo68XjFi3cYyIU+gCXid3kWmMJGXKBifurWOEsBowUCk49XAE/62q0bOo3Xe5eV/QsW97nXoOVCPK+VuDDc4luiIN258BHfbRt03NOzHh4aISTlSpbe305XzsoEdtWkvrudw2/keHvq5Dv/KMdb69ST+epr2J2Ln9a0uFEc4vLZfowF/MKs/SNzZWNzWWVZHjWGuQgsWcUDZVsorWUhbaCj5Oy++CBfQMEI0g75eWRb69OT4gtwE3/072lbEUhDLpBFOouInwEOEPi+GlMnNH9lGFDlUlSU/Ozu1SGdgkGZOgsgXT5mqoYnpvEySfBE1n2m/s+OW1TcVwCjHa8hirfBMHQMY6NhDNXqZhknp7gY/tSupNe2ksJT4XaSglPoOJtp0nb/OVbylOSshlhw4LLfIB8A4xRXCyNQZcqFH4hrBGs5/LfsdCFkrnX1LG5yML4YOUKjwXOknSCyD1+MNazltpWwNZmaDcrlw0ngOm8585X//FI1VNx9dZ+fU4SunaWNBy5VUl9DwOy+NUhTHfQRxfaNcdUTeVzxFtvIHEA6Z2/DH9JiCnZwD9+2Zrp7EM/ccWO/RQwxoIRSEFAfkgv7cNDfTbp1lgxB7T6gSJc8JaqMFe+4QziKpDg5Ej6F8TsveEPr8lnNDqXHfY4JAqNPzylXhfRzwZMgnjF0hUZNOPR8McxfYp+TxynkrXeeR8Hjkfwf/DjZzLNURfo2PtE+w42rTzZq/+KTGy+q6m/Txn3lZxnjOf58xJ+vOc+X81Z47fBydzasI2CGXs6UuHPsag3sxf1rQfYMttHx8Cfnp7ehmulqH+y6hvTfYAum3Rk5XY6/c2cJ4n7KpAUgN7zGkqIvah7wWFWsKuBCL6vwEAAP//5moWdA=="
}
