// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package purestorage

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "purestorage", asset.ModuleFieldsPri, AssetPurestorage); err != nil {
		panic(err)
	}
}

// AssetPurestorage returns asset data.
// This is the base64 encoded zlib format compressed contents of module/purestorage.
func AssetPurestorage() string {
	return "eJzsWk1z2zYQvftX7OSeP6BDZzJpZ9pD2rRxc9XA5MrEGF9ZLG2rv74DUKIlEaAYinDdjHjwgbDfe1gsHhZLv4cH3K7AtYSeLYl7vAFgyQpX8O7g7bsbAEKFwuMK7pDFDUCNviLpWFqzgp9uAOAQB7StWxXgNhJV7VfxF96DERpPCcPDW4cruCfbut2bBP4x2CGgIBJb379O4YXndA77J8nVPQPkUwmHMvBZaKfwaGyv5QG3T5bqk7ER5vD80gF2pINZNygUNyVmPUAem3UM0bqyhskqhZSc/qmoHOghsGfBrR8Mj0f0zMz2z5eIDXYD3OBuvlA1WD1k5YSfZcT8LjTupaBhydusiEckL60po+NrBw7SbCxpwSmivRBt60LR+GTrGA3rkM5rUOVEKJB1WI6NPEnq48zX1ki2y6X9E0lGv3ZIa49VdnrKmvuZ6dbqO6QQ4o4KHBJ4rKwZBmsvqvVYRUnxT9b2dFJL6PokK7Kdjk5T5JqQB7Zl13LBiP0RCabEiVDUr7N2kWmKJGnKBuc3MzE2LEcMtBacGpzAfys1ehbafZeb9wkd4vhK+RyoJqTztxZbXNfojo7gpVT9GdBhiH5sat6JKl3IzLG0SjhRpY61y6fzcQc96dBqrOdyx/ivO/R9HvqtZ9T58iY9vEx5E7Fz59eRCiOcbyzn66wlzCrP0hc2VrUay6rIcew11ILFmrBuq2QW7aVslBU8T8vPggX0DBCNIO+XlkW+vJkfkNuAm9+TfWY0grBOOsESKr5EeIjw58VwI83akX2UoUKVSdKLV+e2kQYOSaYsUNmE6dZqLGN6bxNUPwlazrTf2PXLK5uK4RJilOUpVvkmLoCMOhYQ7WClYZF8e4GP5Upqp70UljU+Fykoa3wGE207T96tV76kuLNWoUhtyikSduiwUSIfAO8QUyt+sTUGXNAofEuo0QzXsj+xkIVU+U3K+DwzET7UtQzjQiVJegEkH39Yy3krZWsgKxOU262LxnPGdP4z5+s7xqlsmp9n5efjKKXrYELN1stKqPXdltHHrgpjvoKYn2ifd0QQiSBHdLADiUdMbf41/UtATvcA+v1mtVNYhv5jhx1qqHENhKKQgoB8lt/blkbq7cssMGJPKXWCxDWhFnK01r7gDiJ1KDByBP02IXtP6PNHwgWlzucdNjikCg2/fI0a6og3QyZh/AaJihz68WqYozi+JV9bzkvpuracry3nGfw/XMu5XEH0NTrWkODE0ZbtN3v5T4mW1XcV7dc+87GKa5/52mdO0l/7zP+rPnP8PriYUxN2QShjT3/t0KcY1Jv5z5ruA2y54+NDwE8fTy/N1TLUfxv5rc1eQI8terEUe/3aBq79hFMVSHLkjLlMRcQ+972gUEm4S4GI/m8AAAD//1vLM1k="
}
