// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package horizon

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "horizon", asset.ModuleFieldsPri, AssetHorizon); err != nil {
		panic(err)
	}
}

// AssetHorizon returns asset data.
// This is the base64 encoded zlib format compressed contents of module/horizon.
func AssetHorizon() string {
	return "eJx8j0GugyAYhPecYuLeC7B4u3cQWqaViELwN609faNoo5b0W84fvhlqtJw0mpDcK/QKECeeGtWaVApI9DQDNS4UowDL4ZpcFBd6jT8FYHuPLtjRUwE3R28HvRxr9KbjvmRGpkiNewpjXJOC9yg6yGi8NJ+45Js5b98odmW+zOcJ+xl8mi4uP96Tt7ScHiHZ0+1H88x/FuZS9Q4AAP//oFZvBw=="
}
