// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package horizon

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "horizon", asset.ModuleFieldsPri, AssetHorizon); err != nil {
		panic(err)
	}
}

// AssetHorizon returns asset data.
// This is the base64 encoded zlib format compressed contents of module/horizon.
func AssetHorizon() string {
	return "eJy8Ws2O5CYQvs9T+AU2l9zmECnaRMllpSj7ACUayjYaoBA/Pdv79BG2u21juxs6szuHSGnXV0Dx1S/7qXnDy2vTk5Pfybw0TZBB4fIHhwqZx9fmhIG9NI1Az520QZK5iTWaRFT40jStRCX860vTfGoM0ytNTRMuFl+bzlG0w/+vdP290jVp+mWQm7XOejkZgzxBwaM7oxu+btc4WGWGNyO8kaYlp1n6aQIul50XTv+dfrqu9oaXd3IiE/SBheiLRBeH4RRNyECKTJchQjQGFdQDBbYsqgAcXZCt5CzkpzkRKWQm3+Kh/NLWmbU/z6DBvjeptWnnVc5MSXH7dX9HmTS0jvQGIpb7XMsHuic92ykwqfLru3PWP0ZAw04UQxN63HLs8fHR+Zl/R6yZ5U9Rqq25ltLzcfxbIAuWSNV5yoRsErLYSRaXeI/3xb4kpLeKXaAcMB+lSD59K/Nqio6XiaJhJ4W5Jfbdy2MI0nQVfPs6IZqW3EC3xdUeM0ygwoAgDVhHnUPvi71tPA5wJdEEcOiDkwO7y1UwpegddFRBWoXg0Se6e7DoIPqFgzxSNCFhdW2PvIUrigI0M6zD8iAzopj3sjMVsOsONxe7f7Wbyx3QW1psb3Ze0tI7OrCkJL8sPh+ZZeVdU6xCATfTSo0Uw4fr09LEgH5HoTQBuxUJ1rxJDPEQKHEPA2jGe2l2NeWX8hQDHyubnIkcOGwd+v66J2BtQAeKOmrbKtNdFZEHIf1braI8XlpHgTipJ2n4zwSv42G++N4N3SHPVKDkWqqUZIThPZHHe6qOL7kPWgHjHL2HPKKX4K/856QUO5EbkudTmhwagQ7dr3uwY1t0Tgo4dzY+t3/NvoGJ+oQOqAVNRgZyde6bVDj0pOJwdmqBmQuQwau6h+e51RXGB6YUCmDWqlRYbhP8nZz5+wyaVTXSNGxV5jzMoqsy5JEv1hZ1Np6U9P1ONjxC4DfkMQzZ2bLQF+NaqXBIoduw0CoWAl4TXsblugJyAn107ZicGwplT47epgBfCpk8fjhdKeYa/QvFlzV58ba6VHzllLrbW471mmBD+350c3njNoCaFejIGRSNHgU7ndsR86rqNibEbqF6JP8DvHN2AB6dDBfoWMB3dqk0618jqqwXFqSZNFB1mlpTXe+u+Pg7ZXcJYJN5S0A+bIcNh6MWF4YKMxPfa+yXxWkZRDEfbnWsiG4v6+yMWlLKS82iAIeaAqpLUSsYDYuhRxOGuUlZ+yiFwoc7uxUEIwvroni3pe7Paf0rxmiMB3nGJ4ZilpO0T+BOAzOeGcJVDpeugSMHHsWOHxpfU6HnDFMbwOGcriDG3mSlC5Ep4JhWKePo+fMg/NEVRk2WrZ03DdWn4QgxFu5mHCGWT8AsuZyJ6wp9UUiB93loPohNvmYLSbFlziM45Irp/dbn3no1smfNQaBVdNG4ccJ9iJJahgo3/HeK6DnwyA2to7NMHJKmgwGz8YG8a1oPc8jiGNN9JXzkVwCuUpuFpkt1afV25hhMjnU4tMEq7YhcZeXzddTQcMZ7fGi3bZ96P8DcHjWSdvDyO4I+FZ5t8bABdEbnpHjyhWODPjre3lvK/66YsyakLHJ+GYV/flYXxlcN86sbpfLisbiYnZzRdOAvPqB+CgTM8V4G5CG6smXrW74RMTwOTaObIthYpQJ+s+gkpuT0pCKN3qdwceuWNG18qhCJpk9pUgwqwEeb0lphQrBMusHwxVTgZFrZRYcCThc4emIumkuUVazTY8RtblwXVL+M6KvLD+164Tvrqsqq6dx78qGuJ60aSV03djXImAbXN/hIx162qtOgUZO7PM4hC4T0PnFNGjivStcjki5TNfSkBPDoA2n5fb8hP3yecpgy16qR3WllV8tplo5hhvpz5ZqPFuuRqZ3LzN8Q8n8zcv1bkfe3xYdmq3n7vLCcdzJtFa6+Hc/BH6yc/v4cFY6LvvwXAAD//56aKKs="
}
