package health

import (
	"time"
)

type Serial string

type CMSData struct {
	loadIndexes                LoadIndexes_JSON
	loadIndexSummaries         LoadIndexSummaries_JSON
	logOnSummaries             LogOnSummaries_JSON
	machineDetails             MachineDetails_JSON
	machineMetricDetails       MachineMetricDetails_JSON
	machineSummaries           MachineSummaries_JSON
	machineMetricSummary       MachineMetricSummary_JSON
	resourceUtilizationSummary ResourceUtilizationSummary_JSON
	resourceUtilization        ResourceUtilization_JSON
	sessionActivitySummaries   SessionActivitySummaries_JSON
	sessionFailureDetails      SessionsDetails_JSON
	sessionMetricDetails       SessionMetricDetails_JSON
	sessionDetails             SessionsDetails_JSON
	serverOSDesktopSummaries   ServerOSDesktopSummaries_JSON
}

type LoadIndexes_JSON struct {
	OdataContext     string `json:"@odata.context,omitempty"`
	OdataCount       int    `json:"@odata.count,omitempty"`
	Message          string
	LoadIndexEntries []LoadIndexEntry `json:"value,omitempty"`
}
type LoadIndexEntry struct {
	ID                 int        `json:"Id,omitempty"`
	EffectiveLoadIndex float64    `json:"EffectiveLoadIndex,omitempty"`
	CPU                float64    `json:"Cpu,omitempty"`
	Memory             float64    `json:"Memory,omitempty"`
	Disk               float64    `json:"Disk,omitempty"`
	Network            float64    `json:"Network,omitempty"`
	SessionCount       int        `json:"SessionCount,omitempty"`
	MachineID          string     `json:"MachineId,omitempty"`
	CreatedDate        *time.Time `json:"CreatedDate,omitempty"`
	ModifiedDate       *time.Time `json:"ModifiedDate,omitempty"`
}

type LoadIndexSummaries_JSON struct {
	OdataContext string `json:"@odata.context,omitempty"`
	OdataCount   int    `json:"@odata.count,omitempty"`
	Message      string
	Value        []struct {
		ID              int        `json:"Id,omitempty"`
		SummaryDate     *time.Time `json:"SummaryDate,omitempty"`
		MachineId       string     `json:"MachineId,omitempty"`
		SumCount        int        `json:"SumCount,omitempty"`
		SumLoadIndex    int        `json:"SumLoadIndex,omitempty"`
		SumCpu          int        `json:"SumCpu,omitempty"`
		SumNetwork      int        `json:"SumNetwork,omitempty"`
		SumDisk         int        `json:"SumDisk,omitempty"`
		SumMemory       int        `json:"SumMemory,omitempty"`
		SumSessionCount int        `json:"SumSessionCount,omitempty"`
		Granularity     int        `json:"Granularity,omitempty"`
		CreatedDate     *time.Time `json:"CreatedDate,omitempty"`
		ModifiedDate    *time.Time `json:"ModifiedDate,omitempty"`
	} `json:"value,omitempty"`
}

type LogOnSummaries_JSON struct {
	OdataContext          string `json:"@odata.context,omitempty"`
	OdataCount            int    `json:"@odata.count,omitempty"`
	Message               string
	LogOnSummariesEntries []LogOnSummariesEntry `json:"value,omitempty"`
}

type LogOnSummariesEntry struct {
	ID                     int        `json:"Id,omitempty"`
	SummaryDate            *time.Time `json:"SummaryDate,omitempty"`
	DesktopGroupID         string     `json:"DesktopGroupId,omitempty"`
	TotalDuration          float64    `json:"TotalDuration,omitempty"`
	TotalCount             int        `json:"TotalCount,omitempty"`
	BrokeringDuration      float64    `json:"BrokeringDuration,omitempty"`
	BrokeringCount         int        `json:"BrokeringCount,omitempty"`
	VMStartDuration        float64    `json:"VMStartDuration,omitempty"`
	VMPowerOnDuration      float64    `json:"VMPowerOnDuration,omitempty"`
	VMRegistrationDuration float64    `json:"VMRegistrationDuration,omitempty"`
	VMStartCount           int        `json:"VMStartCount,omitempty"`
	HdxDuration            float64    `json:"HdxDuration,omitempty"`
	HdxCount               int        `json:"HdxCount,omitempty"`
	AuthenticationDuration float64    `json:"AuthenticationDuration,omitempty"`
	AuthenticationCount    int        `json:"AuthenticationCount,omitempty"`
	GpoDuration            float64    `json:"GpoDuration,omitempty"`
	GpoCount               int        `json:"GpoCount,omitempty"`
	LogOnScriptsDuration   float64    `json:"LogOnScriptsDuration,omitempty"`
	LogOnScriptsCount      int        `json:"LogOnScriptsCount,omitempty"`
	InteractiveDuration    float64    `json:"InteractiveDuration,omitempty"`
	InteractiveCount       int        `json:"InteractiveCount,omitempty"`
	ProfileLoadDuration    float64    `json:"ProfileLoadDuration,omitempty"`
	ProfileLoadCount       int        `json:"ProfileLoadCount,omitempty"`
	Granularity            int        `json:"Granularity,omitempty"`
	//CreatedDate            *time.Time `json:"CreatedDate,omitempty"`
	//ModifiedDate           *time.Time `json:"ModifiedDate,omitempty"`
}

// AutoGenerated represents the structure of the JSON response from the Citrix CMS API for session details.
type MachineDetails_JSON struct {
	OdataContext string `json:"@odata.context,omitempty"`
	OdataCount   int    `json:"@odata.count,omitempty"`
	Message      string
	Value        []struct {
		ID                           string     `json:"Id,omitempty"`
		Sid                          string     `json:"Sid,omitempty"`
		Name                         string     `json:"Name,omitempty"`
		DNSName                      string     `json:"DnsName,omitempty"`
		LifecycleState               int        `json:"LifecycleState,omitempty"`
		IPAddress                    string     `json:"IPAddress,omitempty"`
		HostedMachineID              string     `json:"HostedMachineId,omitempty"`
		HostingServerName            string     `json:"HostingServerName,omitempty"`
		HostedMachineName            string     `json:"HostedMachineName,omitempty"`
		IsAssigned                   bool       `json:"IsAssigned,omitempty"`
		IsInMaintenanceMode          bool       `json:"IsInMaintenanceMode,omitempty"`
		IsPendingUpdate              bool       `json:"IsPendingUpdate,omitempty"`
		AgentVersion                 string     `json:"AgentVersion,omitempty"`
		AssociatedUserFullNames      string     `json:"AssociatedUserFullNames,omitempty"`
		AssociatedUserNames          string     `json:"AssociatedUserNames,omitempty"`
		AssociatedUserUPNs           string     `json:"AssociatedUserUPNs,omitempty"`
		CurrentRegistrationState     int        `json:"CurrentRegistrationState,omitempty"`
		RegistrationStateChangeDate  *time.Time `json:"RegistrationStateChangeDate,omitempty"`
		LastDeregisteredCode         int        `json:"LastDeregisteredCode,omitempty"`
		LastDeregisteredDate         *time.Time `json:"LastDeregisteredDate,omitempty"`
		CurrentPowerState            int        `json:"CurrentPowerState,omitempty"`
		CurrentSessionCount          int        `json:"CurrentSessionCount,omitempty"`
		ControllerDNSName            string     `json:"ControllerDnsName,omitempty"`
		PoweredOnDate                *time.Time `json:"PoweredOnDate,omitempty"`
		PowerStateChangeDate         *time.Time `json:"PowerStateChangeDate,omitempty"`
		FunctionalLevel              int        `json:"FunctionalLevel,omitempty"`
		FailureDate                  *time.Time `json:"FailureDate,omitempty"`
		WindowsConnectionSetting     int        `json:"WindowsConnectionSetting,omitempty"`
		IsPreparing                  bool       `json:"IsPreparing,omitempty"`
		FaultState                   int        `json:"FaultState,omitempty"`
		OSType                       string     `json:"OSType,omitempty"`
		CurrentLoadIndexID           int        `json:"CurrentLoadIndexId,omitempty"`
		CatalogID                    string     `json:"CatalogId,omitempty"`
		DesktopGroupID               string     `json:"DesktopGroupId,omitempty"`
		HypervisorID                 string     `json:"HypervisorId,omitempty"`
		LastPowerActionCompletedDate *time.Time `json:"LastPowerActionCompletedDate,omitempty"`
		LastUpgradeState             int        `json:"LastUpgradeState,omitempty"`
		LastUpgradeStateChangeDate   *time.Time `json:"LastUpgradeStateChangeDate,omitempty"`
		Hash                         string     `json:"Hash,omitempty"`
		MachineRole                  int        `json:"MachineRole,omitempty"`
		CreatedDate                  *time.Time `json:"CreatedDate,omitempty"`
		ModifiedDate                 *time.Time `json:"ModifiedDate,omitempty"`
		CurrentLoadIndex             struct {
			ID                 int        `json:"Id,omitempty"`
			EffectiveLoadIndex int        `json:"EffectiveLoadIndex,omitempty"`
			CPU                float64    `json:"Cpu,omitempty"`
			Memory             float64    `json:"Memory,omitempty"`
			Disk               float64    `json:"Disk,omitempty"`
			Network            float64    `json:"Network,omitempty"`
			SessionCount       int        `json:"SessionCount,omitempty"`
			MachineID          string     `json:"MachineId,omitempty"`
			CreatedDate        *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate       *time.Time `json:"ModifiedDate,omitempty"`
		} `json:"CurrentLoadIndex,omitempty"`
		Catalog struct {
			ID                    string     `json:"Id,omitempty"`
			Name                  string     `json:"Name,omitempty"`
			LifecycleState        int        `json:"LifecycleState,omitempty"`
			ProvisioningType      int        `json:"ProvisioningType,omitempty"`
			PersistentUserChanges int        `json:"PersistentUserChanges,omitempty"`
			IsMachinePhysical     bool       `json:"IsMachinePhysical,omitempty"`
			AllocationType        int        `json:"AllocationType,omitempty"`
			SessionSupport        int        `json:"SessionSupport,omitempty"`
			ProvisioningSchemeID  string     `json:"ProvisioningSchemeId,omitempty"`
			ZoneUID               string     `json:"ZoneUid,omitempty"`
			ZoneName              string     `json:"ZoneName,omitempty"`
			CreatedDate           *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate          *time.Time `json:"ModifiedDate,omitempty"`
		} `json:"Catalog,omitempty"`
		DesktopGroup struct {
			ID                  string     `json:"Id,omitempty"`
			Name                string     `json:"Name,omitempty"`
			IsRemotePC          bool       `json:"IsRemotePC,omitempty"`
			DesktopKind         int        `json:"DesktopKind,omitempty"`
			LifecycleState      int        `json:"LifecycleState,omitempty"`
			SessionSupport      int        `json:"SessionSupport,omitempty"`
			DeliveryType        int        `json:"DeliveryType,omitempty"`
			IsInMaintenanceMode bool       `json:"IsInMaintenanceMode,omitempty"`
			MachineCost         float64    `json:"MachineCost,omitempty"`
			AutoscaleTagID      int        `json:"AutoscaleTagId,omitempty"`
			CreatedDate         *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate        *time.Time `json:"ModifiedDate,omitempty"`
		} `json:"DesktopGroup,omitempty"`
		Hypervisor struct {
			ID             string     `json:"Id,omitempty"`
			Name           string     `json:"Name,omitempty"`
			Type           string     `json:"Type,omitempty"`
			LifecycleState int        `json:"LifecycleState,omitempty"`
			CreatedDate    *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate   *time.Time `json:"ModifiedDate,omitempty"`
		} `json:"Hypervisor,omitempty"`
		MachineCost struct {
			MachineID                  string     `json:"MachineId,omitempty"`
			SpecID                     int        `json:"SpecId,omitempty"`
			CostPerHour                float64    `json:"CostPerHour,omitempty"`
			PowerOnComputeCostPerHour  float64    `json:"PowerOnComputeCostPerHour,omitempty"`
			PowerOnStorageCostPerHour  float64    `json:"PowerOnStorageCostPerHour,omitempty"`
			PowerOffStorageCostPerHour float64    `json:"PowerOffStorageCostPerHour,omitempty"`
			CreatedDate                *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate               *time.Time `json:"ModifiedDate,omitempty"`
		} `json:"MachineCost,omitempty"`
	} `json:"value,omitempty"`
}

// AutoGenerated represents the structure of the JSON response from the Citrix CMS API for health data.
type MachineMetricDetails_JSON struct {
	OdataContext         string `json:"@odata.context,omitempty"`
	OdataCount           int    `json:"@odata.count,omitempty"`
	Message              string
	MachineMetricEntries []MachineMetricEntry `json:"value,omitempty"`
}

type MachineMetricEntry struct {
	MachineID     string     `json:"MachineId,omitempty"`
	CollectedDate *time.Time `json:"CollectedDate,omitempty"`
	Iops          float64    `json:"Iops,omitempty"`
	Latency       float64    `json:"Latency,omitempty"`
}

type MachineSummaries_JSON struct {
	OdataContext            string `json:"@odata.context,omitempty"`
	OdataCount              int    `json:"@odata.count,omitempty"`
	Message                 string
	MachineSummariesEntries []MachineSummariesEntry `json:"value,omitempty"`
}

type MachineSummariesEntry struct {
	ID                             int        `json:"Id,omitempty"`
	SummaryDate                    *time.Time `json:"SummaryDate,omitempty"`
	DesktopGroupID                 string     `json:"DesktopGroupId,omitempty"`
	PoweredOnMachinesCount         int        `json:"PoweredOnMachinesCount,omitempty"`
	RegisteredMachinesCount        int        `json:"RegisteredMachinesCount,omitempty"`
	MachinesInMaintenanceModeCount int        `json:"MachinesInMaintenanceModeCount,omitempty"`
	MachinesCount                  int        `json:"MachinesCount,omitempty"`
	Granularity                    int        `json:"Granularity,omitempty"`
	//CreatedDate                    *time.Time `json:"CreatedDate,omitempty"`
	//ModifiedDate                   *time.Time `json:"ModifiedDate,omitempty"`
}

type MachineMetricSummary_JSON struct {
	OdataContext                string `json:"@odata.context,omitempty"`
	OdataCount                  int    `json:"@odata.count,omitempty"`
	Message                     string
	MachineMetricSummaryEntries []MachineMetricSummaryEntry `json:"value,omitempty"`
}

type MachineMetricSummaryEntry struct {
	MachineID   string     `json:"MachineId,omitempty"`
	SummaryDate *time.Time `json:"SummaryDate,omitempty"`
	AvgIops     float64    `json:"AvgIops,omitempty"`
	PeakIops    float64    `json:"PeakIops,omitempty"`
	AvgLatency  float64    `json:"AvgLatency,omitempty"`
}

type ResourceUtilizationSummary_JSON struct {
	OdataContext                      string `json:"@odata.context,omitempty"`
	OdataCount                        int    `json:"@odata.count,omitempty"`
	Message                           string
	ResourceUtilizationSummaryEntries []ResourceUtilizationSummaryEntry `json:"value,omitempty"`
}

type ResourceUtilizationSummaryEntry struct {
	MachineID            string     `json:"MachineId,omitempty"`
	SummaryDate          *time.Time `json:"SummaryDate,omitempty"`
	DesktopGroupID       string     `json:"DesktopGroupId,omitempty"`
	AvgPercentCPU        float64    `json:"AvgPercentCpu,omitempty"`
	PeakPercentCPU       float64    `json:"PeakPercentCpu,omitempty"`
	AvgUsedMemory        float64    `json:"AvgUsedMemory,omitempty"`
	PeakUsedMemory       float64    `json:"PeakUsedMemory,omitempty"`
	AvgTotalMemory       float64    `json:"AvgTotalMemory,omitempty"`
	AvgLogOnDurationInMs float64    `json:"AvgLogOnDurationInMs,omitempty"`
	//CreatedDate          *time.Time `json:"CreatedDate,omitempty"`
	//ModifiedDate         *time.Time `json:"ModifiedDate,omitempty"`
}

type ResourceUtilization_JSON struct {
	OdataContext               string `json:"@odata.context,omitempty"`
	OdataCount                 int    `json:"@odata.count,omitempty"`
	Message                    string
	ResourceUtilizationEntries []ResourceUtilizationEntry `json:"value,omitempty"`
}
type ResourceUtilizationEntry struct {
	MachineID     string     `json:"MachineId,omitempty"`
	CollectedDate *time.Time `json:"CollectedDate,omitempty"`
	PercentCPU    float64    `json:"PercentCpu,omitempty"`
	UsedMemory    float64    `json:"UsedMemory,omitempty"`
	TotalMemory   float64    `json:"TotalMemory,omitempty"`
	//CreatedDate    *time.Time `json:"CreatedDate,omitempty"`
	//ModifiedDate   *time.Time `json:"ModifiedDate,omitempty"`
	DesktopGroupID string `json:"DesktopGroupId,omitempty"`
}

type SessionActivitySummaries_JSON struct {
	OdataContext                    string `json:"@odata.context,omitempty"`
	OdataCount                      int    `json:"@odata.count,omitempty"`
	Message                         string
	SessionActivitySummariesEntries []SessionActivitySummariesEntry `json:"value,omitempty"`
}

type SessionActivitySummariesEntry struct {
	ID                       int        `json:"Id,omitempty"`
	SummaryDate              *time.Time `json:"SummaryDate,omitempty"`
	DesktopGroupID           string     `json:"DesktopGroupId,omitempty"`
	ConnectedSessionCount    int        `json:"ConnectedSessionCount,omitempty"`
	DisconnectedSessionCount int        `json:"DisconnectedSessionCount,omitempty"`
	ConcurrentSessionCount   int        `json:"ConcurrentSessionCount,omitempty"`
	TotalLogOnDuration       float64    `json:"TotalLogOnDuration,omitempty"`
	TotalLogOnCount          int        `json:"TotalLogOnCount,omitempty"`
	Granularity              int        `json:"Granularity,omitempty"`
	//CreatedDate              *time.Time `json:"CreatedDate,omitempty"`
	//ModifiedDate             *time.Time `json:"ModifiedDate,omitempty"`
}

// AutoGenerated represents the structure of the JSON response from the Citrix CMS API for session details.
type SessionsDetails_JSON struct {
	OdataContext string `json:"@odata.context,omitempty"`
	OdataCount   int    `json:"@odata.count,omitempty"`
	Message      string
	Value        []struct {
		SessionKey                string     `json:"SessionKey,omitempty"`
		StartDate                 *time.Time `json:"StartDate,omitempty"`
		LogOnDuration             int        `json:"LogOnDuration,omitempty"`
		EndDate                   *time.Time `json:"EndDate,omitempty"`
		ExitCode                  int        `json:"ExitCode,omitempty"`
		FailureID                 int        `json:"FailureId,omitempty"`
		FailureDate               *time.Time `json:"FailureDate,omitempty"`
		ConnectionState           int        `json:"ConnectionState,omitempty"`
		SessionIdleTime           *time.Time `json:"SessionIdleTime,omitempty"`
		ConnectionStateChangeDate *time.Time `json:"ConnectionStateChangeDate,omitempty"`
		LifecycleState            int        `json:"LifecycleState,omitempty"`
		CurrentConnectionID       int        `json:"CurrentConnectionId,omitempty"`
		UserID                    int        `json:"UserId,omitempty"`
		MachineID                 string     `json:"MachineId,omitempty"`
		SessionType               int        `json:"SessionType,omitempty"`
		IsAnonymous               bool       `json:"IsAnonymous,omitempty"`
		PublishedDesktopID        int        `json:"PublishedDesktopId,omitempty"`
		CreatedDate               *time.Time `json:"CreatedDate,omitempty"`
		ModifiedDate              *time.Time `json:"ModifiedDate,omitempty"`
		Failure                   struct {
			ID                         int        `json:"Id,omitempty"`
			ConnectionFailureEnumValue int        `json:"ConnectionFailureEnumValue,omitempty"`
			Category                   int        `json:"Category,omitempty"`
			CreatedDate                *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate               *time.Time `json:"ModifiedDate,omitempty"`
		} `json:"Failure,omitempty"`
		CurrentConnection struct {
			ID                        int        `json:"Id,omitempty"`
			ClientName                string     `json:"ClientName,omitempty"`
			ClientAddress             string     `json:"ClientAddress,omitempty"`
			ClientPublicIP            string     `json:"ClientPublicIP,omitempty"`
			ClientVersion             string     `json:"ClientVersion,omitempty"`
			ClientPlatform            string     `json:"ClientPlatform,omitempty"`
			ClientISP                 string     `json:"ClientISP,omitempty"`
			ClientLocationCountry     string     `json:"ClientLocationCountry,omitempty"`
			ClientLocationCity        string     `json:"ClientLocationCity,omitempty"`
			ConnectedViaHostName      string     `json:"ConnectedViaHostName,omitempty"`
			ConnectedViaIPAddress     string     `json:"ConnectedViaIPAddress,omitempty"`
			LaunchedViaHostName       string     `json:"LaunchedViaHostName,omitempty"`
			LaunchedViaIPAddress      string     `json:"LaunchedViaIPAddress,omitempty"`
			IsReconnect               bool       `json:"IsReconnect,omitempty"`
			IsSecureIca               bool       `json:"IsSecureIca,omitempty"`
			Protocol                  string     `json:"Protocol,omitempty"`
			LogOnStartDate            *time.Time `json:"LogOnStartDate,omitempty"`
			LogOnEndDate              *time.Time `json:"LogOnEndDate,omitempty"`
			BrokeringDuration         int        `json:"BrokeringDuration,omitempty"`
			BrokeringDate             *time.Time `json:"BrokeringDate,omitempty"`
			DisconnectCode            int        `json:"DisconnectCode,omitempty"`
			DisconnectDate            *time.Time `json:"DisconnectDate,omitempty"`
			VMStartStartDate          *time.Time `json:"VMStartStartDate,omitempty"`
			VMPoweredOnDate           *time.Time `json:"VMPoweredOnDate,omitempty"`
			VMStartEndDate            *time.Time `json:"VMStartEndDate,omitempty"`
			ClientSessionValidateDate *time.Time `json:"ClientSessionValidateDate,omitempty"`
			ServerSessionValidateDate *time.Time `json:"ServerSessionValidateDate,omitempty"`
			EstablishmentDate         *time.Time `json:"EstablishmentDate,omitempty"`
			HdxStartDate              *time.Time `json:"HdxStartDate,omitempty"`
			HdxEndDate                *time.Time `json:"HdxEndDate,omitempty"`
			AuthenticationDuration    int        `json:"AuthenticationDuration,omitempty"`
			GpoStartDate              *time.Time `json:"GpoStartDate,omitempty"`
			GpoEndDate                *time.Time `json:"GpoEndDate,omitempty"`
			LogOnScriptsStartDate     *time.Time `json:"LogOnScriptsStartDate,omitempty"`
			LogOnScriptsEndDate       *time.Time `json:"LogOnScriptsEndDate,omitempty"`
			ProfileLoadStartDate      *time.Time `json:"ProfileLoadStartDate,omitempty"`
			ProfileLoadEndDate        *time.Time `json:"ProfileLoadEndDate,omitempty"`
			InteractiveStartDate      *time.Time `json:"InteractiveStartDate,omitempty"`
			InteractiveEndDate        *time.Time `json:"InteractiveEndDate,omitempty"`
			SessionKey                string     `json:"SessionKey,omitempty"`
			CreatedDate               *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate              *time.Time `json:"ModifiedDate,omitempty"`
			ConnectionFailureLog      struct {
				ID                         int        `json:"Id,omitempty"`
				SessionKey                 string     `json:"SessionKey,omitempty"`
				FailureDate                *time.Time `json:"FailureDate,omitempty"`
				UserID                     int        `json:"UserId,omitempty"`
				MachineID                  string     `json:"MachineId,omitempty"`
				ConnectionFailureEnumValue int        `json:"ConnectionFailureEnumValue,omitempty"`
				CreatedDate                *time.Time `json:"CreatedDate,omitempty"`
				ModifiedDate               *time.Time `json:"ModifiedDate,omitempty"`
			} `json:"ConnectionFailureLog,omitempty"`
		} `json:"CurrentConnection,omitempty"`
		User struct {
			ID           int        `json:"Id,omitempty"`
			Sid          string     `json:"Sid,omitempty"`
			Upn          string     `json:"Upn,omitempty"`
			UserName     string     `json:"UserName,omitempty"`
			FullName     string     `json:"FullName,omitempty"`
			Domain       string     `json:"Domain,omitempty"`
			CreatedDate  *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate *time.Time `json:"ModifiedDate,omitempty"`
		} `json:"User,omitempty"`
		Machine struct {
			ID                           string     `json:"Id,omitempty"`
			Sid                          string     `json:"Sid,omitempty"`
			Name                         string     `json:"Name,omitempty"`
			DNSName                      string     `json:"DnsName,omitempty"`
			LifecycleState               int        `json:"LifecycleState,omitempty"`
			IPAddress                    string     `json:"IPAddress,omitempty"`
			HostedMachineID              string     `json:"HostedMachineId,omitempty"`
			HostingServerName            string     `json:"HostingServerName,omitempty"`
			HostedMachineName            string     `json:"HostedMachineName,omitempty"`
			IsAssigned                   bool       `json:"IsAssigned,omitempty"`
			IsInMaintenanceMode          bool       `json:"IsInMaintenanceMode,omitempty"`
			IsPendingUpdate              bool       `json:"IsPendingUpdate,omitempty"`
			AgentVersion                 string     `json:"AgentVersion,omitempty"`
			AssociatedUserFullNames      string     `json:"AssociatedUserFullNames,omitempty"`
			AssociatedUserNames          string     `json:"AssociatedUserNames,omitempty"`
			AssociatedUserUPNs           string     `json:"AssociatedUserUPNs,omitempty"`
			CurrentRegistrationState     int        `json:"CurrentRegistrationState,omitempty"`
			RegistrationStateChangeDate  *time.Time `json:"RegistrationStateChangeDate,omitempty"`
			LastDeregisteredCode         int        `json:"LastDeregisteredCode,omitempty"`
			LastDeregisteredDate         *time.Time `json:"LastDeregisteredDate,omitempty"`
			CurrentPowerState            int        `json:"CurrentPowerState,omitempty"`
			CurrentSessionCount          int        `json:"CurrentSessionCount,omitempty"`
			ControllerDNSName            string     `json:"ControllerDnsName,omitempty"`
			PoweredOnDate                *time.Time `json:"PoweredOnDate,omitempty"`
			PowerStateChangeDate         *time.Time `json:"PowerStateChangeDate,omitempty"`
			FunctionalLevel              int        `json:"FunctionalLevel,omitempty"`
			FailureDate                  *time.Time `json:"FailureDate,omitempty"`
			WindowsConnectionSetting     int        `json:"WindowsConnectionSetting,omitempty"`
			IsPreparing                  bool       `json:"IsPreparing,omitempty"`
			FaultState                   int        `json:"FaultState,omitempty"`
			OSType                       string     `json:"OSType,omitempty"`
			CurrentLoadIndexID           int        `json:"CurrentLoadIndexId,omitempty"`
			CatalogID                    string     `json:"CatalogId,omitempty"`
			DesktopGroupID               string     `json:"DesktopGroupId,omitempty"`
			HypervisorID                 string     `json:"HypervisorId,omitempty"`
			LastPowerActionCompletedDate *time.Time `json:"LastPowerActionCompletedDate,omitempty"`
			LastUpgradeState             int        `json:"LastUpgradeState,omitempty"`
			LastUpgradeStateChangeDate   *time.Time `json:"LastUpgradeStateChangeDate,omitempty"`
			Hash                         string     `json:"Hash,omitempty"`
			MachineRole                  int        `json:"MachineRole,omitempty"`
			CreatedDate                  *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate                 *time.Time `json:"ModifiedDate,omitempty"`
			CurrentLoadIndex             struct {
				ID                 int        `json:"Id,omitempty"`
				EffectiveLoadIndex int        `json:"EffectiveLoadIndex,omitempty"`
				CPU                int        `json:"Cpu,omitempty"`
				Memory             int        `json:"Memory,omitempty"`
				Disk               int        `json:"Disk,omitempty"`
				Network            int        `json:"Network,omitempty"`
				SessionCount       int        `json:"SessionCount,omitempty"`
				MachineID          string     `json:"MachineId,omitempty"`
				CreatedDate        *time.Time `json:"CreatedDate,omitempty"`
				ModifiedDate       *time.Time `json:"ModifiedDate,omitempty"`
			} `json:"CurrentLoadIndex,omitempty"`
			Catalog struct {
				ID                    string     `json:"Id,omitempty"`
				Name                  string     `json:"Name,omitempty"`
				LifecycleState        int        `json:"LifecycleState,omitempty"`
				ProvisioningType      int        `json:"ProvisioningType,omitempty"`
				PersistentUserChanges int        `json:"PersistentUserChanges,omitempty"`
				IsMachinePhysical     bool       `json:"IsMachinePhysical,omitempty"`
				AllocationType        int        `json:"AllocationType,omitempty"`
				SessionSupport        int        `json:"SessionSupport,omitempty"`
				ProvisioningSchemeID  string     `json:"ProvisioningSchemeId,omitempty"`
				ZoneUID               string     `json:"ZoneUid,omitempty"`
				ZoneName              string     `json:"ZoneName,omitempty"`
				CreatedDate           *time.Time `json:"CreatedDate,omitempty"`
				ModifiedDate          *time.Time `json:"ModifiedDate,omitempty"`
			} `json:"Catalog,omitempty"`
			DesktopGroup struct {
				ID                  string     `json:"Id,omitempty"`
				Name                string     `json:"Name,omitempty"`
				IsRemotePC          bool       `json:"IsRemotePC,omitempty"`
				DesktopKind         int        `json:"DesktopKind,omitempty"`
				LifecycleState      int        `json:"LifecycleState,omitempty"`
				SessionSupport      int        `json:"SessionSupport,omitempty"`
				DeliveryType        int        `json:"DeliveryType,omitempty"`
				IsInMaintenanceMode bool       `json:"IsInMaintenanceMode,omitempty"`
				MachineCost         float64    `json:"MachineCost,omitempty"`
				AutoscaleTagID      int        `json:"AutoscaleTagId,omitempty"`
				CreatedDate         *time.Time `json:"CreatedDate,omitempty"`
				ModifiedDate        *time.Time `json:"ModifiedDate,omitempty"`
			} `json:"DesktopGroup,omitempty"`
			Hypervisor struct {
				ID             string     `json:"Id,omitempty"`
				Name           string     `json:"Name,omitempty"`
				Type           string     `json:"Type,omitempty"`
				LifecycleState int        `json:"LifecycleState,omitempty"`
				CreatedDate    *time.Time `json:"CreatedDate,omitempty"`
				ModifiedDate   *time.Time `json:"ModifiedDate,omitempty"`
			} `json:"Hypervisor,omitempty"`
			MachineCost struct {
				MachineID                  string     `json:"MachineId,omitempty"`
				SpecID                     int        `json:"SpecId,omitempty"`
				CostPerHour                int        `json:"CostPerHour,omitempty"`
				PowerOnComputeCostPerHour  int        `json:"PowerOnComputeCostPerHour,omitempty"`
				PowerOnStorageCostPerHour  int        `json:"PowerOnStorageCostPerHour,omitempty"`
				PowerOffStorageCostPerHour int        `json:"PowerOffStorageCostPerHour,omitempty"`
				CreatedDate                *time.Time `json:"CreatedDate,omitempty"`
				ModifiedDate               *time.Time `json:"ModifiedDate,omitempty"`
			} `json:"MachineCost,omitempty"`
		} `json:"Machine,omitempty"`
		SessionMetrics []struct {
			ID              int        `json:"Id,omitempty"`
			CollectedDate   *time.Time `json:"CollectedDate,omitempty"`
			IcaRttMS        int        `json:"IcaRttMS,omitempty"`
			IcaLatency      int        `json:"IcaLatency,omitempty"`
			ClientL7Latency int        `json:"ClientL7Latency,omitempty"`
			ServerL7Latency int        `json:"ServerL7Latency,omitempty"`
			SessionID       string     `json:"SessionId,omitempty"`
			CreatedDate     *time.Time `json:"CreatedDate,omitempty"`
			ModifiedDate    *time.Time `json:"ModifiedDate,omitempty"`
		} `json:"SessionMetrics,omitempty"`
		SessionRecordingServer struct {
			SessionKey                 string     `json:"SessionKey,omitempty"`
			SessionRecordingServerName string     `json:"SessionRecordingServerName,omitempty"`
			CreatedDate                *time.Time `json:"CreatedDate,omitempty"`
		} `json:"SessionRecordingServer,omitempty"`
		PublishedDesktopName struct {
			ID            int    `json:"Id,omitempty"`
			PublishedName string `json:"PublishedName,omitempty"`
		} `json:"PublishedDesktopName,omitempty"`
		SessionMetricsLatest struct {
			SessionKey         string      `json:"SessionKey,omitempty"`
			ClientL7Latency    int         `json:"ClientL7Latency,omitempty"`
			CloudConnectorName string      `json:"CloudConnectorName,omitempty"`
			CreatedDate        *time.Time  `json:"CreatedDate,omitempty"`
			EdtMtu             string      `json:"EdtMtu,omitempty"`
			GatewayPopName     string      `json:"GatewayPopName,omitempty"`
			HdxConnectionType  int         `json:"HdxConnectionType,omitempty"`
			HdxProtocolName    string      `json:"HdxProtocolName,omitempty"`
			ModifiedDate       **time.Time `json:"ModifiedDate,omitempty"`
			ServerL7Latency    int         `json:"ServerL7Latency,omitempty"`
		} `json:"SessionMetricsLatest,omitempty"`
	} `json:"value,omitempty"`
}

// AutoGenerated represents the structure of the JSON response from the Citrix CMS API for health data.
type SessionMetricDetails_JSON struct {
	OdataContext         string `json:"@odata.context,omitempty"`
	OdataCount           int    `json:"@odata.count,omitempty"`
	Message              string
	SessionMetricEntries []SessionMetricEntry `json:"value,omitempty"`
}

type SessionMetricEntry struct {
	ID              int        `json:"Id,omitempty"`
	CollectedDate   *time.Time `json:"CollectedDate,omitempty"`
	IcaRttMS        float64    `json:"IcaRttMS,omitempty"`
	IcaLatency      float64    `json:"IcaLatency,omitempty"`
	ClientL7Latency float64    `json:"ClientL7Latency,omitempty"`
	ServerL7Latency float64    `json:"ServerL7Latency,omitempty"`
	SessionID       string     `json:"SessionId,omitempty"`
	CreatedDate     *time.Time `json:"CreatedDate,omitempty"`
	ModifiedDate    *time.Time `json:"ModifiedDate,omitempty"`
	Session         struct {
		SessionKey                string     `json:"SessionKey,omitempty"`
		StartDate                 *time.Time `json:"StartDate,omitempty"`
		LogOnDuration             int        `json:"LogOnDuration,omitempty"`
		EndDate                   *time.Time `json:"EndDate,omitempty"`
		ExitCode                  int        `json:"ExitCode,omitempty"`
		FailureID                 int        `json:"FailureId,omitempty"`
		FailureDate               *time.Time `json:"FailureDate,omitempty"`
		ConnectionState           int        `json:"ConnectionState,omitempty"`
		SessionIdleTime           *time.Time `json:"SessionIdleTime,omitempty"`
		ConnectionStateChangeDate *time.Time `json:"ConnectionStateChangeDate,omitempty"`
		LifecycleState            int        `json:"LifecycleState,omitempty"`
		CurrentConnectionID       int        `json:"CurrentConnectionId,omitempty"`
		UserID                    int        `json:"UserId,omitempty"`
		MachineID                 string     `json:"MachineId,omitempty"`
		SessionType               int        `json:"SessionType,omitempty"`
		IsAnonymous               bool       `json:"IsAnonymous,omitempty"`
		PublishedDesktopID        int        `json:"PublishedDesktopId,omitempty"`
		CreatedDate               *time.Time `json:"CreatedDate,omitempty"`
		ModifiedDate              *time.Time `json:"ModifiedDate,omitempty"`
	} `json:"Session,omitempty"`
}

type ServerOSDesktopSummaries_JSON struct {
	OdataContext string `json:"@odata.context,omitempty"`
	OdataCount   int    `json:"@odata.count,omitempty"`
	Message      string
	Value        []struct {
		ID                          int        `json:"Id,omitempty"`
		SummaryDate                 *time.Time `json:"SummaryDate,omitempty"`
		DesktopGroupId              string     `json:"DesktopGroupId,omitempty"`
		PeakConcurrentInstanceCount int        `json:"PeakConcurrentInstanceCount,omitempty"`
		TotalUsageDuration          float64    `json:"TotalUsageDuration,omitempty"`
		TotalLaunchesCount          int        `json:"TotalLaunchesCount,omitempty"`
		StartingInstanceCount       int        `json:"StartingInstanceCount,omitempty"`
		Granularity                 int        `json:"Granularity,omitempty"`
		CreatedDate                 *time.Time `json:"CreatedDate,omitempty"`
		ModifiedDate                *time.Time `json:"ModifiedDate,omitempty"`
	} `json:"value,omitempty"`
}
