// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package citrix_cms

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "citrix_cms", asset.ModuleFieldsPri, AssetCitrixCms); err != nil {
		panic(err)
	}
}

// AssetCitrixCms returns asset data.
// This is the base64 encoded zlib format compressed contents of module/citrix_cms.
func AssetCitrixCms() string {
	return "eJx8j02OhCAUhPecouLeC7CY3ZxjwkjNSAQhgGm9fUfpH5o2/S3rJV/V6zFxkxhMjmb9GVwSQDbZUqJ7hp0AIi1VosQvsxKAZhqiCdn4WeJLAKgscF4vlgL4M7Q6yePeY1aOTdtO3gIl/qNfwi05sb+6at9IZfP4iM98O+0Hd067Cm/mdkI9g6ty4Xi6pmyZuF181M3tQ/POdxGWUnENAAD//yiPc7c="
}
